POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name": "Joaahn",
    "username": "Doqe",
    "email": "johndygoeqweqe4444@example.com",
    "password": "aaaaaaaaaaaaaaaaaaaaaa"
}